# Generated by Django 5.0 on 2024-01-01 04:46

import datetime
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='CheckQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_answer', models.CharField(max_length=2)),
                ('true_answer', models.CharField(max_length=2)),
                ('is_true', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CheckTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('true_answers', models.PositiveIntegerField(default=0)),
                ('percentage', models.PositiveBigIntegerField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400, verbose_name='savol')),
                ('answer_a', models.CharField(max_length=250, verbose_name='a javob')),
                ('answer_b', models.CharField(max_length=250, verbose_name='b javob')),
                ('answer_c', models.CharField(max_length=250, verbose_name='c javob')),
                ('answer_d', models.CharField(max_length=250, verbose_name='d javob')),
                ('true_answer', models.CharField(max_length=250, verbose_name="to'g'ri javob")),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='sarlavha')),
                ('maximum_attemps', models.PositiveIntegerField(verbose_name='maksimum harakatlar soni')),
                ('pass_percentage', models.PositiveIntegerField(default=60)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='boshlanish sanasi')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2024, 1, 3, 4, 46, 8, 574404, tzinfo=datetime.timezone.utc), verbose_name='tugash sanasi')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
            },
        ),
    ]
